server:
  port : 8082

eureka:
   client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
              defaultZone: http://localhost:8761/eureka/
   instance: localhost
spring:
  application: 
    name: RENTAL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/Capflix
    username: capflix
    password: 1234
    driver-class-name: org.postgresql.Driver


logging:
  level:
    org.springframework: INFO
#    org.hibernate: DEBUG
    {main package path}: INFO

datasource:
  hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
  ddl-auto : update
  show-sql : false
  format-sql : true
